
baseURL = "https://www.catalystedge.org/"
languageCode = "en-us"
title = "Catalyst Edge"
theme = "PaperMod"
enableRobotsTXT = true
defaultContentLanguage = "en"

[pagination]
  pagerSize = 10

[params]
  author = "Catalyst Edge"
  description = "Professional development platform for Indian mid to senior finance professionals."
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  comments = false
  assets = { favicon = "favicon.ico", customCSS = ["css/custom.css"] }

[params.logo]
  logo = "images/catalystedge-logo.png"
  alt = "Catalyst Edge Logo"

[params.homeInfoParams]
  Title = "Strategic Learning for Finance Professionals"
  Content = "Courses and resources tailored for mid to senior-level finance leaders in India. Practical, focused, and expert-led."

[[menu.main]]
  name = "Courses"
  url = "/courses/"
  weight = 1

[[menu.main]]
  name = "Resources"
  url = "/resources/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3

[[menu.main]]
  name = "Testimonials"
  url = "/testimonials/"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 6

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.socialIcons]
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/company/catalystedgeorg"
